insert into department(name) values('software')
insert into department(name) values('mechanical')
insert into department(name) values('chemical')
insert into department(name) values('civil')
insert into department(name) values('electronics')
insert into department(name) values('management')